blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/tomer-yechiel/pino-sentry-transport/discussions
    about: Please discuss non bug-related topics there
