name: Pino sentry transport

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  pino-sentry-transport:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: volta-cli/action@v4
      - run: npm ci

      - name: Dependencies audit
        run: npm audit

      - name: Build
        run: npm run build

      - name: Biome check
        run: npm run check

      - name: Spell check
        run: npm run spell:check

      - name: Test
        run: npm run test


      - name: Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          npx changeset version
          git push --follow-tags
          npx changeset publish
